# Generated by Django 3.0.7 on 2020-07-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200703_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='shop/static/shop/1.jpg', upload_to='shop/images'),
        ),
    ]
