# Generated by Django 3.0.7 on 2020-07-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200703_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.IntegerField(default='', max_length=13)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
