# Generated by Django 3.0.7 on 2020-07-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0005_auto_20200714_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_Image',
            field=models.ImageField(default='user/profiles/IMG_20170511_085612.jpg', upload_to='user/profiles'),
        ),
    ]
